[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
itertools = "0.10.1"
nom = "7.1.0"
chrono = "0.4.19"
nalgebra = "*"
